# Generated by Django 4.1.5 on 2023-03-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='demo',
            field=models.CharField(blank=True, default='N/A', max_length=30, null=True, verbose_name='Demo'),
        ),
    ]
